In [1]:
import tensorflow as tf
import numpy as np

#### Converting from tensorflow Tensor to numpy array and from numpy array to Tensor

In [2]:
# Creating the Tensor
num1 = tf.constant([[1, 2], [3, 4], [5, 6]])
num1

<tf.Tensor 'Const:0' shape=(3, 2) dtype=int32>

In [3]:
# Converting from tensorflow Tensor to numpy array.
sess = tf.Session()
with sess.as_default():
    num2 = num1.eval()
    print(num2)

[[1 2]
 [3 4]
 [5 6]]


In [4]:
# numpy array
num2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
# From numpy array to Tensor
num3 = tf.convert_to_tensor(num2)
with tf.Session() as sess:
    print(sess.run(num3))

[[1 2]
 [3 4]
 [5 6]]


In [6]:
# Tensor
num3

<tf.Tensor 'Const_1:0' shape=(3, 2) dtype=int32>