In [1]:
import tensorflow as tf

In [2]:
x1 = tf.ones((10, 10))
x1 = tf.to_int32(x1)
with tf.Session() as sess:
  print("The matrix of ones is: \n {}" .format(sess.run(x1)))
  print("\n The trace of this matrix is {}.".format(sess.run(tf.trace(x1))))

The matrix of ones is: 
 [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]

 The trace of this matrix is 10.


In [3]:
print(x1.shape)
print(x1.dtype)

(10, 10)
<dtype: 'int32'>


In [4]:
x2 = tf.zeros((10, 10))
x2 = tf.to_int32(x2) 
with tf.Session() as sess:
  print("The matrix of zeros is: \n {}" .format(sess.run(x2)))
  print("\n The trace of this matrix is {}.".format(sess.run(tf.trace(x2))))

The matrix of zeros is: 
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

 The trace of this matrix is 0.


In [5]:
print(x2.shape)
print(x2.dtype)

(10, 10)
<dtype: 'int32'>


In [6]:
x3 = tf.fill([10, 10], 8)

with tf.Session() as sess:
  print("The matrix fill with 8 is: \n {}" .format(sess.run(x3)))
  print("\n The trace of this matrix is {}.".format(sess.run(tf.trace(x3))))

The matrix fill with 8 is: 
 [[8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]]

 The trace of this matrix is 80.


In [7]:
print(x3.shape)
print(x3.dtype)

(10, 10)
<dtype: 'int32'>


In [8]:
x4 = tf.eye(10)
x4 = tf.to_int32(x4)
with tf.Session() as sess:
  print("The matrix of ones along the main diagonal is: \n {}" .format(sess.run(x4)))
  print("\n The trace of this matrix is {}.".format(sess.run(tf.trace(x4))))

The matrix of ones along the main diagonal is: 
 [[1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]]

 The trace of this matrix is 10.


In [9]:
print(x4.shape)
print(x4.dtype)

(10, 10)
<dtype: 'int32'>


In [10]:
# create a 1-D tensor.
x41 = tf.constant([1, 2, 3, 4, 5, 6])
# create a 2-D tensor.
x42 = tf.constant(-5, shape=[3, 3])
with tf.Session() as sess:
  print("create a 1-D tensor {}\n".format(sess.run(x41)))
  print("create a 2-D tensor \n {}".format(sess.run(x42)))

create a 1-D tensor [1 2 3 4 5 6]

create a 2-D tensor 
 [[-5 -5 -5]
 [-5 -5 -5]
 [-5 -5 -5]]


In [11]:
matmult = tf.matmul(x3, x4)
with tf.Session() as sess:
  print("The matrix multiplication of x3 and x4 is: \n {} \n".format(sess.run(matmult)))
  print("The trace of this matrix is {}.".format(sess.run(tf.trace(matmult))))

The matrix multiplication of x3 and x4 is: 
 [[8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]
 [8 8 8 8 8 8 8 8 8 8]] 

The trace of this matrix is 80.


In [12]:
a = tf.constant(3)
b = tf.constant(7)

with tf.Session() as sess:
  print("The sum of a and b is {}.".format(sess.run(tf.add(a, b))))
  print("The product of a and b is {}.".format(sess.run(tf.multiply(a, b))))
  print("The square of a is {}.".format(sess.run(tf.square(a))))

The sum of a and b is 10.
The product of a and b is 21.
The square of a is 9.


In [13]:
# creating a matrix with a specified main diagonal values

diagonal = [1, 2, 3, 4, 5, 6]
x = tf.matrix_diag(diagonal = diagonal) 

with tf.Session() as sess:
  print(sess.run(x))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [14]:
# changing the values on the main diagonal of a matrix

x = tf.zeros((6, 6))
x = tf.matrix_set_diag(x, diagonal = diagonal) 

with tf.Session() as sess:
  print(sess.run(x))

[[1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0. 0.]
 [0. 0. 3. 0. 0. 0.]
 [0. 0. 0. 4. 0. 0.]
 [0. 0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0. 6.]]
